[dependencies]
nalgebra = "0.33.2"
rsa = "0.9.6"

[dependencies.risc0-zkvm]
default-features = false
features = ["std"]
version = "1.1.2"

[dependencies.sha2]
features = ["oid"]
package = "sha2"
version = "0.10.8"

[package]
edition = "2021"
name = "test_project"
version = "0.1.0"

[workspace]
