[patch.crates-io.sha2-v0-10-8]
git = "https://github.com/sp1-patches/RustCrypto-hashes"
package = "sha2"
tag = "sha2-v0.10.8-patch-v1"

[workspace]
members = ["lib", "program", "script"]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "0.7.7"
